[package]
name = "cddl_web_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
cddl = "0.9.1"
cddl-cat = "0.6.1"
cuddle = { git = "https://github.com/hansl/cuddle/" }
cddl-codegen = { git = "https://github.com/connectety/cddl-codegen", branch = "lib" }
tempfile = "3"
zip = "0.6.4"
walkdir = "2.3.3"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]