[package]
name = "cddl_web_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
cddl = "0.9.1"
cddl-cat = "0.6.1"
cuddle = "0.1.0"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json"]
